trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  
- script: |
    git config --global user.email "build@azuredevops.com"
    git config --global user.name "Azure Pipeline"
    git remote add github https://$(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)@github.com/Aniflixx-LLC/aniflixx-backend.git
    git push github HEAD:main --force
  displayName: 'Mirror to GitHub'