-- Drop all views first
DROP VIEW IF EXISTS published_content;
DROP VIEW IF EXISTS scheduled_releases;
DROP VIEW IF EXISTS studio_stats;

-- Drop all indexes
DROP INDEX IF EXISTS idx_regional_availability_unique;
DROP INDEX IF EXISTS idx_studios_clerk_org;
DROP INDEX IF EXISTS idx_studios_slug;
DROP INDEX IF EXISTS idx_studios_active;
DROP INDEX IF EXISTS idx_series_studio;
DROP INDEX IF EXISTS idx_series_slug;
DROP INDEX IF EXISTS idx_series_status;
DROP INDEX IF EXISTS idx_series_type;
DROP INDEX IF EXISTS idx_series_published;
DROP INDEX IF EXISTS idx_episodes_series;
DROP INDEX IF EXISTS idx_episodes_season;
DROP INDEX IF EXISTS idx_episodes_status;
DROP INDEX IF EXISTS idx_episodes_scheduled;
DROP INDEX IF EXISTS idx_episodes_published;
DROP INDEX IF EXISTS idx_team_studio;
DROP INDEX IF EXISTS idx_team_user;
DROP INDEX IF EXISTS idx_regional_series;
DROP INDEX IF EXISTS idx_regional_episode;
DROP INDEX IF EXISTS idx_regional_country;
DROP INDEX IF EXISTS idx_publish_queue_status;
DROP INDEX IF EXISTS idx_publish_queue_scheduled;
DROP INDEX IF EXISTS idx_publish_queue_episode;
DROP INDEX IF EXISTS idx_audit_studio;
DROP INDEX IF EXISTS idx_audit_user;
DROP INDEX IF EXISTS idx_audit_entity;
DROP INDEX IF EXISTS idx_audit_created;
DROP INDEX IF EXISTS idx_analytics_date;
DROP INDEX IF EXISTS idx_analytics_studio;
DROP INDEX IF EXISTS idx_analytics_series;
DROP INDEX IF EXISTS idx_analytics_episode;

-- Drop all tables in reverse dependency order
DROP TABLE IF EXISTS analytics_geographic;
DROP TABLE IF EXISTS analytics_daily;
DROP TABLE IF EXISTS takedowns;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS partner_access;
DROP TABLE IF EXISTS partners;
DROP TABLE IF EXISTS content_relationships;
DROP TABLE IF EXISTS content_warnings;
DROP TABLE IF EXISTS content_languages;
DROP TABLE IF EXISTS episode_versions;
DROP TABLE IF EXISTS release_windows;
DROP TABLE IF EXISTS content_monetization;
DROP TABLE IF EXISTS release_schedules;
DROP TABLE IF EXISTS publish_queue;
DROP TABLE IF EXISTS regional_availability;
DROP TABLE IF EXISTS regional_restrictions;
DROP TABLE IF EXISTS team_members;
DROP TABLE IF EXISTS episodes;
DROP TABLE IF EXISTS seasons;
DROP TABLE IF EXISTS series;
DROP TABLE IF EXISTS studios;